name: batchie
channels:
  - defaults
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - aiohappyeyeballs=2.4.4=py311hecd8cb5_0
  - aiohttp=3.11.10=py311h46256e1_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.16=py311hecd8cb5_0
  - applaunchservices=0.3.0=py311hecd8cb5_0
  - appnope=0.1.4=py311hecd8cb5_0
  - arrow=1.3.0=py311hecd8cb5_0
  - astroid=3.3.8=py311hecd8cb5_0
  - asttokens=3.0.0=py311hecd8cb5_0
  - asyncssh=2.17.0=py311hecd8cb5_0
  - atomicwrites=1.4.0=py_0
  - attrs=24.3.0=py311hecd8cb5_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.16.0=py311hecd8cb5_0
  - backports.tarfile=1.2.0=py311hecd8cb5_0
  - bcrypt=4.3.0=py311h83de92b_0
  - beautifulsoup4=4.13.4=py311hecd8cb5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.1.0=py311hecd8cb5_0
  - bleach=6.2.0=py311hecd8cb5_0
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - certifi=2025.8.3=py311hecd8cb5_0
  - cffi=1.17.1=py311h9205ec4_1
  - chardet=4.0.0=py311hecd8cb5_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py311hecd8cb5_0
  - cloudpickle=3.1.1=py311hecd8cb5_0
  - comm=0.2.1=py311hecd8cb5_0
  - cookiecutter=2.6.0=py311hecd8cb5_1
  - cryptography=45.0.5=py311hc0e11ad_0
  - cyrus-sasl=2.1.28=hd1e62a0_3
  - debugpy=1.8.11=py311h6d0c2b6_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py311hecd8cb5_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.8=py311hecd8cb5_0
  - docstring-to-markdown=0.11=py311hecd8cb5_0
  - docutils=0.21.2=py311hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6d0c2b6_0
  - flake8=7.1.1=py311hecd8cb5_0
  - frozenlist=1.5.0=py311h46256e1_0
  - gettext=0.21.0=h4e8c18a_2
  - glib=2.84.2=h918fcf5_0
  - glib-tools=2.84.2=h918fcf5_0
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py311hecd8cb5_0
  - imagesize=1.4.1=py311hecd8cb5_0
  - importlib-metadata=8.5.0=py311hecd8cb5_0
  - inflection=0.5.1=py311hecd8cb5_0
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.29.5=py311hecd8cb5_1
  - ipython=8.30.0=py311hecd8cb5_0
  - isort=6.0.1=py311hecd8cb5_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jaraco.context=6.0.0=py311hecd8cb5_0
  - jaraco.functools=4.1.0=py311hecd8cb5_0
  - jedi=0.19.2=py311hecd8cb5_0
  - jellyfish=1.1.3=py311h047fda8_0
  - jinja2=3.1.6=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jsonschema=4.25.0=py311hecd8cb5_0
  - jsonschema-specifications=2023.7.1=py311hecd8cb5_0
  - jupyter_client=8.6.3=py311hecd8cb5_0
  - jupyter_core=5.8.1=py311hecd8cb5_0
  - jupyterlab_pygments=0.3.0=py311hecd8cb5_0
  - keyring=25.6.0=py311hecd8cb5_0
  - krb5=1.20.1=h428f121_1
  - libabseil=20250127.0=cxx17_h548131f_0
  - libclang=14.0.6=default_h182e8cd_2
  - libclang13=14.0.6=default_h9f4243d_2
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h04015c4_1
  - libffi=3.4.4=hecd8cb5_1
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libkrb5=1.21.3=h54be378_4
  - libllvm14=14.0.6=h26321d7_4
  - libnghttp2=1.57.0=h9beae6a_0
  - libpng=1.6.39=h6c40b1e_0
  - libpq=17.4=h40f65ae_2
  - libprotobuf=5.29.3=h66a43dd_1
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.11.1=h3a17b82_0
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lmdb=0.9.31=hc8b0dd6_0
  - lz4-c=1.9.4=hcec6c5f_1
  - markdown-it-py=2.2.0=py311hecd8cb5_1
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py311hecd8cb5_0
  - mistune=3.1.2=py311hecd8cb5_0
  - more-itertools=10.3.0=py311hecd8cb5_0
  - multidict=6.1.0=py311h46256e1_0
  - mypy_extensions=1.0.0=py311hecd8cb5_0
  - mysql=8.4.0=h5364baf_2
  - nbclient=0.10.2=py311hecd8cb5_0
  - nbconvert=7.16.6=py311hecd8cb5_0
  - nbconvert-core=7.16.6=py311hecd8cb5_0
  - nbconvert-pandoc=7.16.6=py311hecd8cb5_0
  - nbformat=5.10.4=py311hecd8cb5_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=py311hecd8cb5_0
  - numpydoc=1.9.0=py311he13d532_0
  - openldap=2.6.10=h5897940_0
  - openssl=3.0.17=hee2dfae_0
  - packaging=25.0=py311hecd8cb5_0
  - pandoc=2.12=hecd8cb5_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py311hecd8cb5_0
  - pathspec=0.12.1=py311hecd8cb5_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=py311hecd8cb5_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.7=py311hecd8cb5_0
  - ply=3.11=py311hecd8cb5_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py311h46256e1_0
  - psutil=5.9.0=py311h46256e1_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.12.1=py311hecd8cb5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py311hecd8cb5_0
  - pyflakes=3.2.0=py311hecd8cb5_0
  - pygithub=2.4.0=py311hecd8cb5_0
  - pyjwt=2.10.1=py311hecd8cb5_0
  - pylint=3.3.5=py311hecd8cb5_0
  - pylint-venv=3.0.3=py311hecd8cb5_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py311h46256e1_1
  - pyobjc-core=10.1=py311h46256e1_0
  - pyobjc-framework-cocoa=10.1=py311h9205ec4_0
  - pyobjc-framework-coreservices=10.1=py311h46256e1_0
  - pyobjc-framework-fsevents=10.1=py311hecd8cb5_0
  - pyqt=5.15.10=py311h6d0c2b6_1
  - pyqt5-sip=12.13.0=py311h46256e1_1
  - pyqtwebengine=5.15.10=py311h6d0c2b6_1
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python-fastjsonschema=2.20.0=py311hecd8cb5_0
  - python-lsp-black=2.0.0=py311hecd8cb5_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.12.2=py311he13d532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python.app=3=py311h46256e1_2
  - pytoolconfig=1.2.6=py311hecd8cb5_0
  - pyuca=1.2=py311hecd8cb5_1
  - pyyaml=6.0.2=py311h46256e1_0
  - pyzmq=26.2.0=py311h6d0c2b6_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py311hecd8cb5_0
  - qt-main=5.15.2=hf83fbd5_12
  - qt-webengine=5.15.9=h90a370e_7
  - qtawesome=1.4.0=py311hecd8cb5_0
  - qtconsole=5.6.1=py311hecd8cb5_1
  - qtpy=2.4.1=py311hecd8cb5_0
  - readline=8.3=h49f2429_0
  - referencing=0.30.2=py311hecd8cb5_0
  - requests=2.32.4=py311hecd8cb5_0
  - rich=13.9.4=py311hecd8cb5_0
  - roman-numerals-py=3.1.0=py311hecd8cb5_0
  - rope=1.13.0=py311hecd8cb5_0
  - rpds-py=0.22.3=py311h83de92b_0
  - rtree=1.0.1=py311hecd8cb5_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - sip=6.7.12=py311h6d0c2b6_1
  - six=1.17.0=py311hecd8cb5_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py311hecd8cb5_0
  - sphinx=8.2.3=py311h46256e1_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.0.7=py311hecd8cb5_1
  - spyder-kernels=3.0.5=py311he13d532_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - superqt=0.7.3=py311he13d532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py311he13d532_1
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.4.0=py311hecd8cb5_0
  - tk=8.6.15=h3a5a201_0
  - tomli=2.2.1=py311hecd8cb5_0
  - tomlkit=0.13.2=py311hecd8cb5_0
  - tornado=6.5.1=py311h46256e1_0
  - traitlets=5.14.3=py311hecd8cb5_0
  - typing_extensions=4.12.2=py311hecd8cb5_0
  - ujson=5.10.0=py311h6d0c2b6_1
  - unidecode=1.3.8=py311hecd8cb5_0
  - urllib3=2.5.0=py311hecd8cb5_0
  - watchdog=4.0.2=py311h3333b6a_0
  - wcwidth=0.2.13=py311hecd8cb5_0
  - webencodings=0.5.1=py311hecd8cb5_1
  - whatthepatch=1.0.2=py311hecd8cb5_0
  - wheel=0.45.1=py311hecd8cb5_0
  - wrapt=1.17.0=py311h46256e1_0
  - wurlitzer=3.0.2=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.40.2=py311hecd8cb5_0
  - yarl=1.18.0=py311h46256e1_0
  - zeromq=4.3.5=hcec6c5f_0
  - zipp=3.21.0=py311hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - batchie==0.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - h5py==3.15.1
      - iniconfig==2.3.0
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.6
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pluggy==1.6.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==9.0.1
      - pytest-mock==3.15.1
      - pytz==2025.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sympy==1.14.0
      - torch==2.2.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
prefix: /Users/Prog_ReS.S/anaconda3/envs/batchie
